# Generated by Django 4.2.3 on 2023-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(db_table='quote_tag_association', to='quotes.tag'),
        ),
    ]
